### PR TITLE
Fix handling of paths in generating extension callback URLs

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Code assumes the browser workbench is being served on a URL at path `/`. As a result, when generating extension callback URLs, it
1. Takes the current URL
2. Changes the path to `/oss-dev/callback?<params>` (the path components here are configurable, but it's not relevant right now)

Since we serve Code through the gateway -- one URL with different workspaces distinguished by path components -- this causes extension callback URLs to lead to 404s, since they're 
```
https://<che-gateway>/oss-dev/callback
```

To fix this, we need to change the workbench to use the existing path when generating callback URLs. 

### What issues does this PR fix?
Resolves https://issues.redhat.com/browse/CRW-5334
See also: https://github.com/ansible/vscode-ansible/issues/938

### How to test this PR?
@TamiTakamiya provided a sample extension to verify this functionality: https://github.com/TamiTakamiya/external-uri-sample

Installing the vsix from this repository adds the "External URI sample" action to Code, which generates a toast notification for the callback URL Code has generated. Prior to this change, this is e.g.
```yaml
URI: checode://tamitakamiya.external-uri-sample 
External URI: https://<cluster>.openshiftapps.com/oss-dev/callback?vscode-reqid%3D2%26vscode-scheme%3Dchecode%26vscode-authority%3DTamiTakamiya.external-uri-sample
```
(this URL leads to a 404 on the gateway)

With this change, the external URI is now
```yaml
URI: checode://tamitakamiya.external-uri-sample 
External URI: https://<cluster>.openshiftapps.com/<namespace>/che-code/3100/oss-dev/callback?vscode-reqid%3D1%26vscode-scheme%3Dchecode%26vscode-authority%3DTamiTakamiya.external-uri-sample
```
(note the addition of `/<namespace>/che-code/3100/` to the path -- this URL leads to a page saying "you can close this window now").

Changes for this PR are pushed to `quay.io/amisevsk/che-code:callback-url`. To patch an existing workspace to use these changes, execute:
```bash
oc get dwt che-code-$DEVWORKSPACE_NAME -o yaml \
  | sed 's|quay.io/che-incubator/che-code.*|quay.io/amisevsk/che-code:callback-url|' \
  | oc apply -f -
```

### CODE REVIEW

**Comment by TamiTakamiya** [comment]
@amisevsk Thank you for your update! Is there any test environment we can test our Ansible VS Code extension?  We have updated our staging server (https://stage.ai.ansible.redhat.com) to accept redirect URI pattern `https://*.openshiftapps.com/*/callback`. For testing, an updated Ansible VS Code extension is also needed.   

So if there is a test environment available under `*.openshiftapps.com/`, we can run the test.  If the environment is under a different domain, we can update the server settings.  Please let us know!  Thanks.

**Comment by amisevsk** [comment]
@TamiTakamiya You should be able to test the changes on [Developer Sandbox](https://developers.redhat.com/developer-sandbox), if you have a Red Hat Developers account (free). On the sandbox cluster, there is a Dev Spaces (downstream of Eclipse Che) installation you can access at https://workspaces.openshift.com/ (once you've registered). The testing instructions above should work there -- open a code terminal and paste
```bash
oc get dwt che-code-$DEVWORKSPACE_NAME -o yaml \
  | sed 's|quay.io/che-incubator/che-code.*|quay.io/amisevsk/che-code:callback-url|' \
  | oc apply -f -
```

**Comment by TamiTakamiya** [comment]
@amisevsk Thanks! Let me try.

**Comment by TamiTakamiya** [comment]
@amisevsk I executed the given command in a code terminal but still do not see `/<namespace>/che-code/3100/` inserted in the callback URI.  I guess I missed some setup procedures requires.  Do I need to reboot or do something after issuing the command?
image

**Comment by TamiTakamiya** [comment]
The output of `oc get dwt che-code-$DEVWORKSPACE_NAME -o yaml` in my workspace does not contain the string `quay.io`.

**Comment by TamiTakamiya** [comment]
If  `/<namespace>/che-code/3100/` (in my case it is `/rh-ee-ttakamiy/che-code/3100/`) **was manually inserted when the redirection occurred**, I could go through the OAuth2 Authorization code flow.  So if the code to insert  `/<namespace>/che-code/3100/` is integrated into the product code, we can expect the problem would be resolved.
image

**Comment by TamiTakamiya** [comment]
@amisevsk I could replace `registry.redhat.io/devspaces/code-rhel8` with `quay.io/amisevsk/che-code:callback-url`

**Comment by TamiTakamiya** [comment]
With the `quay.io/amisevsk/che-code:callback-url` + our Staging Lightspeed server + Ansible VS Code Extension local build (2023-0=12-07 version), OAuth2 authorization code flow went through successfully. Thank you!!

https://github.com/che-incubator/che-code/assets/27698807/67441a31-c3c9-40db-93c3-3a1d38d6938f

**Review by RomanNikitenko — APPROVED** [review]

**Comment by amisevsk** [comment]
@TamiTakamiya Ah yes, my bad -- on Dev Spaces the image doesn't come from quay.io, so that find/replace doesn't work. It sounds like you've figured it out in the mean time, but the correct replacement would be 
```bash
oc get dwt che-code-$DEVWORKSPACE_NAME -o yaml \
  | sed 's|registry.redhat.io/devspaces/code-rhel8.*|quay.io/amisevsk/che-code:callback-url|' \
  | oc apply -f -
```

Sorry for the confusion!

**Comment by amisevsk** [comment]
I once again forgot to open the PR from the main fork for PR checks. I've opened https://github.com/che-incubator/che-code/pull/320 which contains the same commits.

**Comment by amisevsk** [comment]
Turns out pushing to the main branch allows PR checks on this (from a fork) PR to run :+1:

**Pull request merged**
