### PR TITLE
chore: Fix an automatic rebase against the upstream

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Fix an automatic rebase against the upstream

### What issues does this PR fix?

https://github.com/eclipse/che/issues/22577

### How to test this PR?
jobs should be happy

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]
Thank you Roman for looking at it!

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
thank you for the reviewing it!

I've found another problem:

image


So, I'm not able to merge my changes as is:

image

I'll have to:
- resolve that problem first
- update my current PR
- ask you again for the review

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
I've resolved conflicts, does it still look good for you to be merged?

if so, I'm going to merge it as soon as the jobs become green.

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy I've resolved conflicts, does it still look good for you to be merged?
> 
> if so, I'm going to merge it as soon as the jobs become green.

Sure, @RomanNikitenko please merge once it's ready. Thx!

**Pull request merged**
