### PR TITLE
deps: Update cross-spawn version

### PR DESCRIPTION
**Pull request by RomanNikitenko**
The changes are for the `7.95.x` branch.

### What does this PR do?
- there are few places where just `patch` version was updated for the `cross-spawn` dependency
- there are also few places where `cross-spawn` version was overridded

### What issues does this PR fix?

https://issues.redhat.com/browse/CRW-7596

### How to test this PR?
I think the `patch` version update - is a minor change.  
About the second case (overridden version) - the changes are related to tests and `dev` dependency `npm-run-all`.
All jobs are green, tests are happy, so, I think the current changes are safe enough.

### Does this PR contain changes that override default upstream Code-OSS behavior?
- [ ] the PR contains changes in the [code](https://github.com/che-incubator/che-code/tree/main/code) folder (you can skip it if your changes are placed in a che extension )
- [ ] the corresponding items were added to the [CHANGELOG.md](https://github.com/che-incubator/che-code/blob/main/.rebase/CHANGELOG.md) file
- [ ] rules for automatic `git rebase` were added to the [.rebase](https://github.com/che-incubator/che-code/tree/main/.rebase) folder

### CODE REVIEW

**Review by vitaliy-guliy — APPROVED** [review]

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [code_3.18/25](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.18/25/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.18/25/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.18/25/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.18/25/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [sync-to-downstream_3.18/245](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/245/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/245/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/245/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.18/245/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [get-sources-rhpkg-container-build_3.18/240](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/240/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/240/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/240/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/240/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3.18-rhel-9/) :: [get-sources-rhpkg-container-build_3.18/240](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/240/): [FAILURE](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.18/240/)<br /><blockquote>code : 3.18 :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=66293834'> Failed in  66293834</a> : code-rhel9-3.18-1 <br /> FAILURE:  ERROR - plugin 'maven_url_sources_metadata' raised an exception: ValueError: Computed sha256 checksum, a097578fa080fe8100075820797fce4393361e2f8ae494f7f8f9d08d069862d0, does not match expected checksum, b5224ea3d857d10e04514342b6ca0f9ce79162657f7b25b75fba32995d4405a7; copied to quay</blockquote>

**Pull request merged**
