### PR TITLE
[superseded] fix: load vs-code webview resources from local host instead of getting them from CDN

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
Forwards requests to the local domain instead of sending them to the CDN.

There are four types of the requests / resources that handled:

- resources to initialize webview and webworker ( with HTTP scheme )
  `${WebviewResourcesBaseURI}oss-dev/static/out/vs/workbench/contrib/webview/browser/pre`

- resources, that are located in the current project ( FILE scheme )
  `file:///projects/web-nodejs-sample/images/default.png`

- resources from a built-in extension ( FILE scheme )
  `file:///checode/checode-linux-libc/extensions/markdown-language-features/media/pre.js`

- resources from installed extension ( FILE scheme )
  `file:///checode/remote/extensions/atlassian.atlascode-3.0.2-universal`

To be able to load resources from installed extension and from the current project it needs to create symlinks to `/project` and to `/checode/remote/extensions` directories ( see changes in assembly.Dockerfile )

Screenshot from 2023-04-05 19-10-28

### What issues does this PR fix?

https://issues.redhat.com/browse/CRW-3885

### How to test this PR?

1. Create a workspace from the repository https://github.com/vitaliy-guliy/web-nodejs-sample/tree/test-webviews
  ( it will use prebuilt [quay.io/vgulyy/che-code:webviews-behind-a-proxy-stable](https://quay.io/vgulyy/che-code:webviews-behind-a-proxy-stable) editor image )

2. Open README.md at the project root, click Open Preview at the right top
3. Install Jira and Bitbucket extension, open Atlassian Settings tab ( webview based )

Before 2 and 3 steps, open the browser console, navigate to Network.
After 2 and 3 check there is no requests to vscode-cdn.net.

### CODE REVIEW

**Review by azatsarynnyy — COMMENTED** [review]
The workspace is failed to start:
image

[`.che/che-editor.yaml`](https://github.com/vitaliy-guliy/web-nodejs-sample/blob/test-webviews/.che/che-editor.yaml) looks outdated. It needs to be adapted to the latest changes, related to the starting VS Code by `post-start` event.
@vitaliy-guliy see the [current version in the plugin-registry](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L150).

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
I don't think it's related to the `post-start` event changes.
I'm able to start my workspace [without adaptation](https://github.com/RomanNikitenko/web-nodejs-sample/blob/testDevfile/.che/che-editor.yaml#L17-L23) to `post-start` event changes: https://github.com/RomanNikitenko/web-nodejs-sample/tree/testDevfile

I would say - it's up to users how they prefer to start their workspaces - it should work for both ways if I haven't missed anything

**Comment by azatsarynnyy** [comment]
@RomanNikitenko I follow the steps provided in `How to test this PR?`

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko I follow the steps provided in `How to test this PR?`

I understand, I also see that the workspace fails, but I don't understand why do you think that it's related to the `post-start` event. My workspace works without any adaptation to the `post-start` event.

**Comment by vitaliy-guliy** [comment]
> The workspace is failed to start: image
> 
> [`.che/che-editor.yaml`](https://github.com/vitaliy-guliy/web-nodejs-sample/blob/test-webviews/.che/che-editor.yaml) looks outdated. It needs to be adapted to the latest changes, related to the starting VS Code by `post-start` event. @vitaliy-guliy see the [current version in the plugin-registry](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L150).

On which instance did you try to create a workspace?

If it is a dogfooding instance, it has some issues that I think needs to be investigated / fixed.
A week ago I got the exact error, but today I get following
Screenshot from 2023-04-05 15-14-42

@olexii4 @tolusha  @svor  could you please take a look?

**Comment by azatsarynnyy** [comment]
> On which instance did you try to create a workspace?

@vitaliy-guliy I use dogfooding instance

**Comment by vitaliy-guliy** [comment]
> > On which instance did you try to create a workspace?
> 
> @vitaliy-guliy I use dogfooding instance

This instance has been refusing to work with my sample for two weeks. I thought it's temporary state.

**Comment by olexii4** [comment]
> > The workspace is failed to start: image
> > [`.che/che-editor.yaml`](https://github.com/vitaliy-guliy/web-nodejs-sample/blob/test-webviews/.che/che-editor.yaml) looks outdated. It needs to be adapted to the latest changes, related to the starting VS Code by `post-start` event. @vitaliy-guliy see the [current version in the plugin-registry](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L150).
> 
> On which instance did you try to create a workspace?
> 
> If it is a dogfooding instance, it has some issues that I think needs to be investigated / fixed. A week ago I got the exact error, but today I get following Screenshot from 2023-04-05 15-14-42
> 
> @olexii4 @tolusha @svor could you please take a look?

@vitaliy-guliy I am working on it https://github.com/eclipse/che/issues/22057

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy I am working on it [eclipse/che#22057](https://github.com/eclipse/che/issues/22057)

A week ago I faced only an issue that @azatsarynnyy mentioned

**Comment by azatsarynnyy** [comment]
A workspace starts successfully on the DevSandbox instance with the provided test project.

**Comment by svor** [comment]
@vitaliy-guliy editor's content is not valid:
screenshot-nimbusweb me-2023 04 05-17_31_18

try to replace in your sample https://github.com/vitaliy-guliy/web-nodejs-sample/blob/test-webviews/.che/che-editor.yaml#L26-L28
```
        env:
          - name: CDN_ENABLED
            value: false
```
with
```
        env:
          - name: CDN_ENABLED
            value: "false"
```

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy editor's content is not valid: 
>
> try to replace
> 
> ```
>         env:
>           - name: CDN_ENABLED
>             value: false
> ```
> 
> with
> 
> ```
>         env:
>           - name: CDN_ENABLED
>             value: "false"
> ```

I would intentionally leave it without quotes ( just to be sure it works for both cases )
How it was valid before and become not valid now?
Just take a look at the devfiles for other editors. There are a dozen samples where the values without quotes.

**Comment by svor** [comment]
>Just take a look at the devfiles for other editors. There are a dozen samples where the values without quotes.

Could you provide an example. As far as I know if the value has type boolean - it should be quoted

**Comment by vitaliy-guliy** [comment]
> Could you provide an example. As far as I know if the value has type boolean - it should be quoted

Ah, OK. I haven't found any other example with boolean-like value.
But then I have a questions. How it was working before?
Why it works fine on developer SandBox instance?

**Comment by vitaliy-guliy** [comment]
@svor @olexii4 thank you for help and pointing me on `devfile.yaml` schema (discused in private).

@RomanNikitenko @azatsarynnyy now the sample works on dogfooding instance.
I just removed the variables from both `devfile.yaml` and `.che/che-editor.yaml`. Those variables are relevant for the next issue I am working on [CRW-4178](https://issues.redhat.com/browse/CRW-4178)

Btw, VS Code `redhat.vscode-yaml` extension does not considered `.che/che-editor.yaml` as inlined `devfile.yaml`, and does not validate it. It's confusing and would nice to have it (low priority).

**Review by azatsarynnyy — COMMENTED** [review]
I tested the PR and I can confirm that it fixes the issue as expected :+1: 

But I'm concerned by the number of changes the PR is going to introduce.
And especially modifications to the internals of VS Code. I'm afraid that it will lead to merge conflicts during the auto-rebase against the upstream and will require resolving them "manually" too often. Even now, there's already a merge conflict appeared.

Currently, I'm experimenting (in my draft PR https://github.com/che-incubator/che-code/pull/206) with another [approach I described previously in the issue comment](https://issues.redhat.com/browse/CRW-3885?focusedId=21960933&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21960933).
I suppose it will do the same work, but with much fewer modifications of VS Code internals. I need some time to verify it. I'll post the results here.

**Comment by vitaliy-guliy** [comment]
> I'm afraid that it will lead to merge conflicts during the auto-rebase against the upstream and will require resolving them "manually" too often. Even now, there's already a merge conflict appeared.

I'm afraid of that as well. Thinking how to simplify it.

> Currently, I'm experimenting (in my draft PR #206) with another [approach I described previously in the issue comment](https://issues.redhat.com/browse/CRW-3885?focusedId=21960933&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21960933). I suppose it will do the same work, but with much fewer modifications of VS Code internals. I need some time to verify it. I'll post the results here.

Thank for pointing me on `workbench-che-config.ts` file, using it I can simplify those changes https://github.com/che-incubator/che-code/pull/196/files#diff-05ff801f67c291f7e6873479a2054ae44e1300c709440aaa92053f9dddfd5481

I think that defining the property in `workbench-che-config.ts` will affect only the first type of resources ([from this directory](https://github.com/che-incubator/che-code/tree/main/code/src/vs/workbench/contrib/webview/browser/pre)), that I described in the PR description.

**Comment by azatsarynnyy** [comment]
> I think that defining the property in workbench-che-config.ts will affect only the first type of resources ([from this directory](https://github.com/che-incubator/che-code/tree/main/code/src/vs/workbench/contrib/webview/browser/pre)), that I described in the PR description.

yes, it seems that just [passing the webview endpoint to the workbench config](https://github.com/che-incubator/che-code/pull/206/files) is not enough. I played a bit with this and it doesn't work OOTB. Needs more investigation.

In [this comment](https://issues.redhat.com/browse/CRW-3885?focusedId=21799737&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21799737), there're a couple of links that may help as well. 

@vitaliy-guliy to solve the problem with the potential rebase conflicts you can look at the rebase rules [here](https://github.com/che-incubator/che-code/tree/main/.rebase). With them, it's possible to apply some modification (like changing the sha value of the `script-src` CSP) after the rebase is performed by [rebase.sh](https://github.com/che-incubator/che-code/blob/main/rebase.sh)

**Comment by vitaliy-guliy** [comment]
Superseded by https://github.com/che-incubator/che-code/pull/208

**Pull request closed without merging**
