### PR TITLE
feat: Add an ability to apply branding using script file

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Add an ability to apply branding using script file.

branding-script

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
FYI it seems there are some shellchecks warnings

maybe add a section into https://github.com/che-incubator/che-code README (like there is one about the rebase script)

**Comment by RomanNikitenko** [comment]
@benoitf 
hello!
> maybe add a section into https://github.com/che-incubator/che-code README (like there is one about the rebase script)

good idea, will do it, thank you!

> FYI it seems there are some shellchecks warnings

could you clarify:
what way do you use to check it?
like - some extension or online resource or...

**Comment by benoitf** [comment]
you can use online https://www.shellcheck.net/ (or install a plug-in in the IDE)

**Comment by benoitf** [comment]
you're free to merge, it's already approved :-)

**Comment by RomanNikitenko** [comment]
> you're free to merge, it's already approved :-)

I'm going to add a section to README first :-)

**Comment by azatsarynnyy** [comment]
@RomanNikitenko let's update the `README.md` by a separate PR and merge this one if it's ready.

**Pull request merged**
