### PR TITLE
fix: remove trailing slash from metrics server endpoint

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
- makes resource monitor working on the dogfooding cluster
- displays properly CPU usage for dev sandbox

Screenshot from 2024-08-16 17-34-29

Screenshot from 2024-08-16 17-43-42

### What issues does this PR fix?

https://github.com/eclipse-che/che/issues/23044
https://github.com/eclipse-che/che/issues/23066

### How to test this PR?
Using the editor image from this PR, create a workspace on the dogfooding and then on the developer sandbox instances.

### Does this PR contain changes that override default upstream Code-OSS behavior?
- [ ] the PR contains changes in the [code](https://github.com/che-incubator/che-code/tree/main/code) folder (you can skip it if your changes are placed in a che extension )
- [ ] the corresponding items were added to the [CHANGELOG.md](https://github.com/che-incubator/che-code/blob/main/.rebase/CHANGELOG.md) file
- [ ] rules for automatic `git rebase` were added to the [.rebase](https://github.com/che-incubator/che-code/tree/main/.rebase) folder

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]
It works well for me, on the dogfooding cluster 👍

**Comment by azatsarynnyy** [comment]
With the editor's `Light Modern` theme, which I have by default for my environments, 
image

it requires some adaptation of the font colors
image

But that's another issue, not related to this patch.

**Review by azatsarynnyy — COMMENTED** [review]
On Dev Sandbox works fine as well

image

image

**Comment by vitaliy-guliy** [comment]
> With the editor's `Light Modern` theme, which I have by default for my environments, image
> 
> it requires some adaptation of the font colors image
> 
> But that's another issue, not related to this patch.

I will create another tiny PR for that

**Pull request merged**
