### PR TITLE
fix: Add peer dependency explicitly to the package.json

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
See https://github.com/che-incubator/che-code/pull/474

### What issues does this PR fix?

https://issues.redhat.com/browse/CRW-7882

### How to test this PR?
I tested adding the dependency to the downstream project - build passed successfully for the corresponding step.

### Does this PR contain changes that override default upstream Code-OSS behavior?
- [x] the PR contains changes in the [code](https://github.com/che-incubator/che-code/tree/main/code) folder (you can skip it if your changes are placed in a che extension )
- [x] the corresponding items were added to the [CHANGELOG.md](https://github.com/che-incubator/che-code/blob/main/.rebase/CHANGELOG.md) file
- [x] rules for automatic `git rebase` were added to the [.rebase](https://github.com/che-incubator/che-code/tree/main/.rebase) folder

### CODE REVIEW

**Review by vitaliy-guliy — APPROVED** [review]

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [code_3.x/1527](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.x/1527/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.x/1527/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.x/1527/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/code_3.x/1527/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [sync-to-downstream_3.x/8420](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8420/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8420/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8420/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8420/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [get-sources-rhpkg-container-build_3.x/8523](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8523/): [Console](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8523/console), [Changes](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8523/changes), [Git Data](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8523/git)

**Comment by devspacesbuild** [comment]
Build [3.19](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-9/) :: [get-sources-rhpkg-container-build_3.x/8523](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8523/): [FAILURE](https://jenkins-csb-crwqe-main.dno.corp.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8523/)<br /><blockquote>code : 3.x :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=66293808'> Failed in  66293808</a> : BREW:BUILD/STATUS:UNKNOWN <br /> FAILURE:; copied to quay</blockquote>

**Pull request merged**
