### PR TITLE
feat: Support running VS Code in ubi9-based containers

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Use:
- Node.js provided by `registry.access.redhat.com/ubi9/nodejs-18`
- `libbrotli` library from the same image
- `LD_LIBRARY_PATH` env variable to define additional shared libs place 

to run VS Code in a user's `ubi9-based` container.

### What issues does this PR fix?

https://github.com/eclipse/che/issues/21778

### How to test this PR?
| Image  | Workspace starts | Devfile registry link | Link to start a workspace |
| :-------------: | :-------------: | :-------------: | :-------------: |
| `registry.access.redhat.com/ubi8`  | +  | - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi8-ld-path)  |
| `registry.access.redhat.com/ubi9`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-ld-path)  |
| `registry.access.redhat.com/ubi9/ubi:9.3-1476`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-ubi-ld-path)  |
| `registry.access.redhat.com/ubi9/ubi-minimal:9.3-1475`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-ubi-minimal-ld-path)  |
| `registry.access.redhat.com/ubi9/podman:9.3-8`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-podman-ld-path)  |
| `registry.access.redhat.com/ubi9/perl-532:1-121`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-perl-532-ld-path)  |
| `registry.access.redhat.com/ubi9/php-81:1-43`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-php-81-ld-path)  |
| `registry.access.redhat.com/ubi9/ruby-30:1-138`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-ruby-30-ld-path)  |
| `registry.access.redhat.com/ubi9/openjdk-21-runtime`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-openjdk-21-runtime-ld-path)  |
| `registry.access.redhat.com/ubi9/nodejs-16:1-143`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-nodejs-16-ld-path)  |
| `registry.access.redhat.com/ubi9/nodejs-18:1-84`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-nodejs-18-ld-path)  |
| `registry.access.redhat.com/ubi9/nodejs-20:1-20`  | +  |  - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-nodejs-20-ld-path)  |
| `registry.access.redhat.com/ubi9/openjdk-11:1.17-1.1705602311`  | +  | - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/ubi9-openjdk-11-ld-path)  |
| `registry.access.redhat.com/ubi9/openjdk-17:1.17-1`  | +  | [Basic Spring Boot](https://registry.devfile.io/viewer/devfiles/community/java-springboot-basic) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/basic-spring-boot)  |
| `registry.access.redhat.com/ubi9/go-toolset:1.19.13-4.1697647145`  | +  | [Go Runtime](https://registry.devfile.io/viewer/devfiles/community/go) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/go-runtime)  |
| `registry.access.redhat.com/ubi8/nodejs-16:latest`  | +  | [Basic Node.js](https://registry.devfile.io/viewer/devfiles/community/nodejs-basic) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/basic-nodejs)  |
| `registry.access.redhat.com/ubi9/python-39:1-161`  | +  | [Python-Django](https://registry.devfile.io/viewer/devfiles/community/python-django) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/python-django)  |
| `registry.access.redhat.com/ubi9/python-39:1-161`  | +  | [Basic Python](https://registry.devfile.io/viewer/devfiles/community/python-basic) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/python-basic)  |
| `registry.access.redhat.com/ubi8/openjdk-17:1.18-2`  | +  | [Quarkus Java](https://registry.devfile.io/viewer/devfiles/community/java-quarkus) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/java-quarkus)  |
| `quay.io/eclipse/che-java11-maven:7.37.2`  | No <br />  [the cause of the problem](https://issues.redhat.com/browse/CRW-5634?focusedId=23842993&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23842993)  | [Vert.x Java](https://registry.devfile.io/viewer/devfiles/community/java-vertx) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/vertx)  |
| `quay.io/jaegertracing/all-in-one:1.50`  | No <br />  [the cause of the problem](https://issues.redhat.com/browse/CRW-5634?focusedId=23841690&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23841690)  | [WildFly Bootable Jar](https://registry.devfile.io/viewer/devfiles/community/java-wildfly-bootable-jar) | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-devfiles/tree/wildfly-bootable)  |
| `docker.io/alpine:3.19.0`  | No | - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/alpine-3-19-ld-path)  |
| `docker.io/node:18.18.2-alpine3.18`  | + | - | [click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/RomanNikitenko/test-redhat-nodejs/tree/alpine-3-18-node-18-ld-path)  |

### CODE REVIEW

**Review by l0rd — APPROVED** [review]
I have tested this PR vscode image on workspaces using alpine, busybox, docker, fedora, golang, openjdk, ubi8, ubi9 and ubuntu base images and if worked on most of them (`docker.io/alpine:3.19.0`, `docker.io/busybox:1.36.1`, `docker.io/docker:24.0.6-dind` are still failing). This is an important improvement compared to what we get trying current vs code image.

Some improvments (for later PRs) could be:
- support recent alpine with new version of `musl` (that should fix `quay.io/jaegertracing/all-in-one:1.50` too)
- support images that don't have neither `openssl` nor `rpm` ([looking for `/usr/lib/libcrypto*` for example](https://gist.github.com/l0rd/89db3c97e3cfd3d1f8197fedd7281659#file-find-libcrypto-version-sh-L49))
- `libc-ubi8` and `libc-ubi9` checode should be renamed `libc-v1` and `libc-v3` as they run on any image using libc, not just on UBI.
- default che-code should be `libc-ubi9`/`libc-v3` instead of the `libc-ubi8` as new images will all have the new version of libc.

**Comment by RomanNikitenko** [comment]
@l0rd 
thank you very much for testing!

I would like to clarify some points for myself:
> support recent alpine with new version of musl (that should fix quay.io/jaegertracing/all-in-one:1.50 too)

It's possible to apply the improvement for the `che-code`, but there is a problem for the downstream.
AFAIK - at the moment we don't have `alpine`-based assembly for the downstream as there is no base image that we can use for the productization process.
So, there is a problem for images, like: 
- `quay.io/jaegertracing/all-in-one:1.50`
- `docker.io/alpine:3.19.0`
- `docker.io/docker:24.0.6-dind`

=====================
> default che-code should be libc-ubi9/libc-v3 instead of the libc-ubi8 as new images will all have the new version of libc.

I'm afraid I didn't get what do you mean here:
- as far as I understand the editor-image contains both: `ubi8` and `ubi9-based` assemblies
- at starting a workspace we just use one of them - it depends on the user's container for running
- so - what `default che-code should be libc-ubi9/libc-v3` means

=====================
> libc-ubi8 and libc-ubi9 checode should be renamed libc-v1 and libc-v3 as they run on any image using libc, not just on UBI.

I'm not sure about `they run on any image using libc`.
For example, we build `ubi8`- based assembly that relies on `(GNU libc) 2.28`, but user's container contains `(GNU libc) 2.17`.
or
Node.js relies on `/lib64/libstdc++.so.6`, the file exists in the user's container, but user gets something like: `/lib64/libstdc++.so.6: version GLIBCXX_3.4.20 not found` - I'm not sure that `LD_LIBRARY_PATH` can resolve this problem. 

So, I consider `ubi8` and `ubi9`-based assemblies as a set of libraries that are required for running Node.js and some VS Code dependencies in a user's `ubi8/ubi9`-based container. 
Like:
 - we build VS Code in the `ubi8` container - then it should work in another `ubi8`-based container as both of them have similar shared libs(version of libs)

**Comment by l0rd** [comment]
> It's possible to apply the improvement for the che-code, but there is a problem for the downstream.

Right. There is no request to support alpine downstream. It's an upstream only issue. 

> it depends on the user's container for running. so - what `default che-code should be libc-ubi9/libc-v3` means?

What I mean is the default when the openssl version is unknown. When the bash script fails to figure out the openssl version (that happens on the ubuntu and busybox images for example) [then it currently defaults to the ubi8 assembly](https://github.com/che-incubator/che-code/blob/ubi9_test/build/scripts/entrypoint-volume.sh#L59). If we change that, and use ubi9 in case of unknown openssl version, any recent ubuntu-based image will work out of the box.

> we build VS Code in the ubi8 container - then it should work in another ubi8-based container as both of them have similar shared libs(version of libs)

Does it matter if the assembly has been built in a ubi8, a fedora or an ubuntu container? che-code built on ubi8 works on images that have `openssl-v1` (e.g. openjdk) and che-code built on ubi9 works on any image with `openssl-v3` (ubuntu, golang, fedora).

**Comment by RomanNikitenko** [comment]
> What I mean is the default when the openssl version is unknown. When the bash script fails to figure out the openssl version (that happens on the ubuntu and busybox images for example) [then it currently defaults to the ubi8 assembly](https://github.com/che-incubator/che-code/blob/ubi9_test/build/scripts/entrypoint-volume.sh#L59). If we change that, and use ubi9 in case of unknown openssl version, any recent ubuntu-based image will work out of the box.

Maybe it's true for ubuntu, but not for the mentioned above `busybox`.
I just tested `docker.io/busybox:1.36.1` for both: `ubi8` and `ubi9` assembly.

There is the same error: 
image

image

So, for the `docker.io/busybox:1.36.1` it doesn't matter - `ubi8` or `ubi9` - we should provide not only `brotli`, but also `libz`. 
 All libs required by Node.js must be present in a user's container:
image

**Comment by RomanNikitenko** [comment]
> Does it matter if the assembly has been built in a ubi8, a fedora or an ubuntu container? che-code built on ubi8 works on images that have openssl-v1 (e.g. openjdk) and che-code built on ubi9 works on any image with openssl-v3 (ubuntu, golang, fedora).

I was not able to run Node.js in the `quay.io/wildfly/wildfly-centos7:26.1` using both: `ubi8` and `ubi9`-based assemblies:

Screenshot 2024-01-24 at 11 18 51

So, I'm not sure we can guarantee that Che-Code can start in **any** user's container. 
It really depends on set of shared libs and their versions in a user's container.
That's why I would start from support for `ubi8` and `ubi9`-based containers.

**Comment by RomanNikitenko** [comment]
@l0rd thank you for the feedback! It's really helpful!

@l0rd @ibuziuk 
So, does it make sense to improve the following **within the current PR**:
- add `libz` related files to both: `ubi8` and `ubi9` assemblies
- add `libbrotli` files to `ubi8` assembly (the same way as it's done for `ubi9` in the current PR)
- use `ubi9` based assembly when the openssl version is unknown

The changes look simple, after applying them I could test it for my table in the PR description.
But I'm not aware what set of images was tested by Mario for the current PR - it makes sense to test them again after updating my PR...

**Comment by ibuziuk** [comment]
> That's why I would start from support for ubi8 and ubi9-based containers.

I believe it makes sense to start with supporting ubi8 and ubi 9 and merge this PR, but we need to create follow up issue - 
for cases that @l0rd described in https://github.com/che-incubator/che-code/pull/324#pullrequestreview-1839378928 

The ultimate goal / story - `As a User I want to specify any popular image in the devfile and use it in my CDE`

Also, please create separate issues for 2 devfile.io devfiles that are currently failing. In the next sprint it would be great to finalize the following epic - https://github.com/eclipse/che/issues/20251  

> But I'm not aware what set of images was tested by Mario for the current PR - it makes sense to test them again after updating my PR...

I think the scripts for testing various images are part of https://github.com/l0rd/cloud-dev-images

**Review by ibuziuk — APPROVED** [review]

**Comment by l0rd** [comment]
@RomanNikitenko I approved this PR so from my point of view that's ok to merge as it is. 

At some point we should support ubuntu-based images (that looks easy, it's just changing the script to use the opensslv3 assembly rather than the opensslv1 when the openssl version is unknown) and alpine-based images (that seams a little bit harder: introduce a new musl assembly that supports openssl v3). 

`busybox` is NOT an ubuntu-based or alpine-based image and it's not a priority at all so you can ignore it.

**Review by azatsarynnyy — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
image

@azatsarynnyy 
it looks like I'm not able to merge the current PR due to `Required` status of the `build (libc, amd64)` check.
so, could you update the repo settings?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy it looks like I'm not able to merge the current PR due to `Required` status of the `build (libc, amd64)` check. so, could you update the repo settings?

@RomanNikitenko done

**Pull request merged**
