### PR TITLE
fix: Use 'replace' operation to provide Che-specific env variables to the extension context

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

### What does this PR do?
`append` operation is used to add env variables to the extension context, but it leads to the bug like:
`PROJECTS_ROOT` variable already exists, its value is `/projects` => `append` operation is applied => the value is:  `/projects/projects`

So, let's use `replace` operation to add Che-specific variables to the extension context.

### What issues does this PR fix?

https://issues.redhat.com/browse/CRW-6025

### How to test this PR?
**Use case 1: Che-specific env variables should have correct value**
- start a workspace with a project
- open a terminal
- check values for `PROJECTS_ROOT`, `WORKSPACE_NAMESPACE`, `WORKSPACE_NAME`, `DASHBOARD_URL` variables
- also see https://issues.redhat.com/browse/CRW-6025 for the context

**Use case 2: terminal should use '/projects' as default directory**
- start an empty workspace
- open a terminal
- check that `pwd` => `/projects`
- also see https://github.com/eclipse-che/che/issues/22819 for the context

**Use case 3: 'Stop Workspace' and 'Restart Workspace' actions work as expected**
- Che-specific env variables are used for those actions, so let's check that the actions still work as expected 
- start a workspace
- `F1` => `Restart Workspace` => the workspace should be restarted
- `F1` => `Stop Workspace` => the workspace should be stopped

### Does this PR contain changes that override default upstream Code-OSS behavior?
- [ ] the PR contains changes in the [code](https://github.com/che-incubator/che-code/tree/main/code) folder (you can skip it if your changes are placed in a che extension )
- [ ] the corresponding items were added to the [CHANGELOG.md](https://github.com/che-incubator/che-code/blob/main/.rebase/CHANGELOG.md) file
- [ ] rules for automatic `git rebase` were added to the [.rebase](https://github.com/che-incubator/che-code/tree/main/.rebase) folder

### CODE REVIEW

**Comment by vitaliy-guliy** [comment]
@RomanNikitenko could you provide a link that can be used to create a workspace?

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 
here you are: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/#/load-factory?che-editor=che-incubator/che-code/insiders&storageType=per-workspace&editor-image=quay.io/che-incubator-pull-requests/che-code:pr-350-amd64&url=https://registry.devfile.io/devfiles/nodejs-nextjs/1.2.1

But, sorry, could you clarify why do you need the link to start a workspace?
For testing it's enough just set PR image to the `Editor Image` field:

image
 

It's super **_easy_** action and super **_flexible_** way for testing.

This way reviewer can:
- use any instance for testing (proxy environment, for example, for some use cases)
- test any devfile
- test any project, 
- use any `tools` image (test `ubi8` vs `ubi9`)
- start a workspace using git repo vs devfile
- start an empty workspace   

I would say it's preferable way for testing a fix or a new functionality, because:
- if reviewer uses a link provided by author of a PR  
then
- reviewer goes through all the same steps that author of a PR already did - the same instance, the same devfile, the same project, the same `tools` container, the same ... for a workspace creation.

From my point of view it's the best way to `reproduce a bug`, but not the best way for testing something.
wdyt?

**Review by azatsarynnyy — APPROVED** [review]
@RomanNikitenko thanks for providing the steps for testing. Below are the results I've got:

Use case 1:

Screenshot 2024-04-25 at 16 38 07

Use case 2:

https://github.com/che-incubator/che-code/assets/1636395/3104d897-bbab-43a1-90cd-e2625cc283d1

Use case 3:
Stop/Restart Workspace commands work as expected.

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy here you are: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/#/load-factory?che-editor=che-incubator/che-code/insiders&storageType=per-workspace&editor-image=quay.io/che-incubator-pull-requests/che-code:pr-350-amd64&url=https://registry.devfile.io/devfiles/nodejs-nextjs/1.2.1
> 
> But, sorry, could you clarify why do you need the link to start a workspace? For testing it's enough just set PR image to the `Editor Image` field:
> 

Usually I test features not only on the dogfooding instance, but on the sandbox as well.
That's why I asked for a factory link.

If somebody else is interested in the feature or the bug fixing that PR provides, he could want to test it.
Providing a simple URI to test the PR is user friendly I think.

**Review by vitaliy-guliy — APPROVED** [review]
Case 1.
Works as expected.

Case 2.
I think we should focus here on `PROJECTS_ROOT` environment variable as well. I've checked it and it can confirm it is properly initialized
```
PROJECTS_ROOT="/projects"
```

Case 3.
Seems actions to restart and stop the workspace work fine.

**Comment by RomanNikitenko** [comment]
> If somebody else is interested in the feature or the bug fixing that PR provides, he could want to test it.

to be honest, I didn't see it during last few _years_, unfortunately...

**Pull request merged**
